import 'package:json_annotation/json_annotation.dart';

@JsonEnum()
enum TechSkill {
  assembly('Assembly'),
  astro('Astro'),
  awk('Awk'),
  batchfile('Batchfile'),
  c('C'),
  cSharp('C#'),
  cpp('C++'),
  cMake('CMake'),
  css('CSS'),
  clojure('Clojure'),
  coffeeScript('CoffeeScript'),
  cuda('Cuda'),
  cython('Cython'),
  dart('Dart'),
  dockerfile('Dockerfile'),
  ejs('EJS'),
  fSharp('F#'),
  glsl('GLSL'),
  gherkin('Gherkin'),
  go('Go'),
  groovy('Groovy'),
  h('H'),
  hlsl('HLSL'),
  html('HTML'),
  hack('Hack'),
  handlebars('Handlebars'),
  innoSetup('Inno Setup'),
  java('Java'),
  javaScript('JavaScript'),
  jinja('Jinja'),
  julia('Julia'),
  jupyterNotebook('Jupyter Notebook'),
  kotlin('Kotlin'),
  less('Less'),
  lex('Lex'),
  lua('Lua'),
  m4('M4'),
  matlab('MATLAB'),
  mdx('MDX'),
  mlir('MLIR'),
  makefile('Makefile'),
  objectiveC('Objective-C'),
  objectiveCpp('Objective-C++'),
  php('PHP'),
  pawn('Pawn'),
  perl('Perl'),
  powerShell('PowerShell'),
  pug('Pug'),
  python('Python'),
  r('R'),
  raku('Raku'),
  roff('Roff'),
  ruby('Ruby'),
  rust('Rust'),
  sCSS('SCSS'),
  scilab('Scilab'),
  shaderLab('ShaderLab'),
  shell('Shell'),
  smPL('SmPL'),
  smarty('Smarty'),
  starlark('Starlark'),
  swift('Swift'),
  tml('TML'),
  tex('TeX'),
  typeScript('TypeScript'),
  unrealScript('UnrealScript'),
  vimSnippet('Vim Snippet'),
  visualBasicDotNet('Visual Basic .NET'),
  xSsed('XSsed'),
  yacc('Yacc');

  const TechSkill(this.language);

  final String language;
}
