import 'package:appwrite_graphql_client/models/types/country.dart';

extension CountryIcon on Country {
  static const package = 'country_icons';

  String _getIconPath(String country) => 'icons/flags/png/$country.png';

  String get icon {
    switch (code) {
      case 'ALB':
        return _getIconPath('al');
      case 'HAI':
        return _getIconPath('ht');
      case 'UZB':
        return _getIconPath('uz');
      case 'ISV':
        return _getIconPath('vi');
      case 'MLT':
        return _getIconPath('mt');
      case 'MAS':
        return _getIconPath('my');
      case 'LIE':
        return _getIconPath('li');
      case 'LUX':
        return _getIconPath('lu');
      case 'PER':
        return _getIconPath('pe');
      case 'PHI':
        return _getIconPath('ph');
      case 'GHA':
        return _getIconPath('gh');
      case 'AZE':
        return _getIconPath('az');
      case 'KOS':
        return _getIconPath('xk');
      case 'CYP':
        return _getIconPath('cy');
      case 'IND':
        return _getIconPath('in');
      case 'PAK':
        return _getIconPath('pk');
      case 'NGR':
        return _getIconPath('ng');
      case 'SRB':
        return _getIconPath('rs');
      case 'TPE':
        return _getIconPath('tw');
      case 'MNE':
        return _getIconPath('me');
      case 'TLS':
        return _getIconPath('tl');
      case 'KGZ':
        return _getIconPath('kg');
      case 'COL':
        return _getIconPath('co');
      case 'SMR':
        return _getIconPath('sm');
      case 'ARM':
        return _getIconPath('am');
      case 'AND':
        return _getIconPath('ad');
      case 'ECU':
        return _getIconPath('ec');
      case 'ISL':
        return _getIconPath('is');
      case 'MDA':
        return _getIconPath('md');
      case 'PUR':
        return _getIconPath('pr');
      case 'MKD':
        return _getIconPath('mk');
      case 'ASA':
        return _getIconPath('as');
      case 'MAD':
        return _getIconPath('mg');
      case 'HKG':
        return _getIconPath('hk');
      case 'HUN':
        return _getIconPath('hu');
      case 'THA':
        return _getIconPath('th');
      case 'MEX':
        return _getIconPath('mx');
      case 'ROU':
        return _getIconPath('ro');
      case 'ISR':
        return _getIconPath('il');
      case 'TTO':
        return _getIconPath('tt');
      case 'BOL':
        return _getIconPath('bo');
      case 'POR':
        return _getIconPath('pt');
      case 'SLO':
        return _getIconPath('si');
      case 'BRA':
        return _getIconPath('br');
      case 'POL':
        return _getIconPath('pl');
      case 'GEO':
        return _getIconPath('ge');
      case 'ARG':
        return _getIconPath('ar');
      case 'CZE':
        return _getIconPath('cz');
      case 'ESP':
        return _getIconPath('es');
      case 'NZL':
        return _getIconPath('nz');
      case 'LTU':
        return _getIconPath('lt');
      case 'SVK':
        return _getIconPath('sk');
      case 'AUT':
        return _getIconPath('at');
      case 'KOR':
        return _getIconPath('kr');
      case 'GBR':
        return _getIconPath('gb');
      case 'CRO':
        return _getIconPath('hr');
      case 'LBN':
        return _getIconPath('lb');
      case 'MGL':
        return _getIconPath('mn');
      case 'IRL':
        return _getIconPath('ie');
      case 'CHI':
        return _getIconPath('cl');
      case 'MAR':
        return _getIconPath('ma');
      case 'AUS':
        return _getIconPath('au');
      case 'BUL':
        return _getIconPath('bg');
      case 'GRE':
        return _getIconPath('gr');
      case 'JPN':
        return _getIconPath('jp');
      case 'NOR':
        return _getIconPath('no');
      case 'ITA':
        return _getIconPath('it');
      case 'CAN':
        return _getIconPath('ca');
      case 'BLR':
        return _getIconPath('by');
      case 'BIH':
        return _getIconPath('ba');
      case 'JAM':
        return _getIconPath('jm');
      case 'MON':
        return _getIconPath('mc');
      case 'TUR':
        return _getIconPath('tr');
      case 'ROC':
        return _getIconPath('ru');
      case 'EST':
        return _getIconPath('ee');
      case 'KAZ':
        return _getIconPath('kz');
      case 'IRI':
        return _getIconPath('ir');
      case 'BEL':
        return _getIconPath('be');
      case 'SUI':
        return _getIconPath('ch');
      case 'SWE':
        return _getIconPath('se');
      case 'FRA':
        return _getIconPath('fr');
      case 'CHN':
        return _getIconPath('cn');
      case 'NED':
        return _getIconPath('nl');
      case 'UKR':
        return _getIconPath('ua');
      case 'LAT':
        return _getIconPath('lv');
      case 'GER':
        return _getIconPath('de');
      case 'ERI':
        return _getIconPath('er');
      case 'KSA':
        return _getIconPath('sa');
      case 'USA':
        return _getIconPath('us');
      case 'FIN':
        return _getIconPath('fi');
      case 'DEN':
        return _getIconPath('dk');
    }

    throw FallThroughError();
  }
}
